import type { Question } from './types';

/**
 * Cola de preguntas abiertas al día de hoy (§5-BIS).
 * Formato obligatorio de cada pregunta, en español llano, sin jerga legal:
 *   Lo que teníamos / Lo que aparece ahora / Por qué importa / Qué documento lo aclararía.
 * Las preguntas que se pueden convertir en una búsqueda de documento, se convierten
 * (campo searchHint).
 */
export const SEED_QUESTIONS: Question[] = [
  {
    id: 'q1',
    declaredBlocks: 6,
    order: 1,
    prompt: 'Nombre, puesto y línea de reporte de cada subordinado directo tuyo en Cellular Hope Institute',
    weHad: 'Un organigrama general de 43 personas en tres unidades (Cellgenic ~20, ISSCA ~16, Cellular Institute ~9). No dice quién te reporta a ti dentro de Cellular Hope Institute.',
    whatAppearsNow: 'No tenemos ni un solo subordinado directo capturado con nombre, puesto y línea de reporte.',
    whyItMatters: 'La teoría ejecutiva se sostiene o se cae aquí: sin subordinados con nombre no hay organigrama, no hay tabla de tiempo y la carta de empleo queda en afirmaciones sin respaldo.',
    clarifyingDocument: 'Organigrama interno de Cellular Hope Institute + CV y título de cada persona que te reporta.',
    searchHint: 'Busca la lista de nómina de CHI o el chat donde se repartieron los puestos del laboratorio y la clínica de Cancún. Con nombre y puesto basta para empezar.',
    targetPath: null,
    impactPath: 'subordinatesForeign',
    kind: 'people',
    blocksLabel: '6 documentos',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q2',
    declaredBlocks: 5,
    order: 2,
    prompt: '¿Cuál es la fecha exacta en que empezaste a trabajar para Cellular Hope Institute?',
    weHad: 'Que trabajas en Cancún para Cellular Hope Institute, sin fecha de inicio.',
    whatAppearsNow: 'El campo de fecha de inicio está vacío.',
    whyItMatters: 'Hay que probar un año continuo de empleo en el extranjero dentro de los tres años previos a la presentación. Sin esta fecha no se puede afirmar ese año.',
    clarifyingDocument: 'Contrato laboral CHI–Sarah, o el primer recibo CFDI timbrado, o el alta del IMSS.',
    searchHint: 'Busca el primer recibo de nómina que te haya emitido CHI, o el correo donde te mandaron el contrato. El día exacto está ahí.',
    targetPath: 'beneficiary.employmentStartDate',
    kind: 'date',
    blocksLabel: '5 documentos',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q3',
    declaredBlocks: 4,
    order: 3,
    prompt: '¿Cuál es tu salario actual y en qué moneda te pagan, pesos o dólares?',
    weHad: 'Nada. El salario actual nunca se registró.',
    whatAppearsNow: 'Campo vacío, y sin moneda.',
    whyItMatters: 'La descripción de puesto, la carta de empleo y la comparación con el salario propuesto en EE.UU. dependen de esta cifra.',
    clarifyingDocument: 'Recibo CFDI de nómina timbrado por el SAT, emisor Cellular Hope Institute, S.A. de C.V.',
    searchHint: 'Toma el recibo de nómina más reciente y lee el importe bruto mensual y la moneda que dice en el papel.',
    targetPath: 'beneficiary.currentSalary',
    kind: 'money',
    blocksLabel: '4 documentos',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q4',
    declaredBlocks: 4,
    order: 4,
    prompt: '¿Estás dada de alta en el IMSS por Cellular Hope Institute? ¿Existe el reporte de semanas cotizadas?',
    weHad: 'Que CHI te emplea y te paga.',
    whatAppearsNow: 'No sabemos si hay alta en el IMSS a nombre de CHI como patrón.',
    whyItMatters: 'El reporte de semanas cotizadas del IMSS es la mejor evidencia individual del expediente para el año continuo de empleo en el extranjero.',
    clarifyingDocument: 'Reporte de semanas cotizadas del IMSS a tu nombre, con CHI como patrón.',
    searchHint: 'Se descarga en línea en el portal del IMSS con tu CURP y NSS. Si no tienes el NSS, aparece en cualquier recibo de nómina.',
    targetPath: 'beneficiary.imssRegistered',
    impactPath: 'beneficiary.employmentStartDate',
    kind: 'boolean',
    blocksLabel: 'Prueba central del año continuo',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q5',
    declaredBlocks: 3,
    order: 5,
    prompt: '¿Qué porcentaje exacto de Cellular Hope Institute es de Global Stem Cells Group? Y si hay un segundo accionista, ¿quién es?',
    weHad: 'RMTG posee el 100% de GSCG, con certificado accionario del 21/08/2021 y respaldo en filings SEC.',
    whatAppearsNow: 'El porcentaje de GSCG sobre CHI está vacío. Bajo ley mexicana una S.A. de C.V. típicamente requiere dos o más accionistas.',
    whyItMatters: 'La relación calificada entre la peticionaria y la empleadora extranjera es el primero de los cinco elementos. Sin el porcentaje real no se puede afirmar el control.',
    clarifyingDocument: 'Libro de accionistas de Cellular Hope Institute, S.A. de C.V., y acta constitutiva.',
    searchHint: 'Está en el libro de registro de acciones que guarda el contador o el notario. No declares 100% sin verlo.',
    targetPath: 'ownershipChain.1.percent',
    kind: 'percent',
    blocksLabel: 'Relación calificada',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q6',
    declaredBlocks: 3,
    order: 6,
    prompt: '¿Cuál es la fecha y el estado de constitución de Global Stem Cells Group, y cuál es su EIN?',
    weHad: 'GSCG es la peticionaria del I-129, constituida en Florida.',
    whatAppearsNow: 'Sin fecha de constitución y sin EIN.',
    whyItMatters: 'La Tab A del fólder (peticionaria estadounidense) no se puede armar sin constitución y EIN, y el EIN de nómina debe coincidir con el del arrendamiento y el I-129.',
    clarifyingDocument: 'Articles of Incorporation de GSCG + carta de asignación de EIN del IRS (CP 575 o 147C).',
    searchHint: 'La fecha aparece gratis en sunbiz.org buscando el nombre de la empresa. El EIN está en la carta del IRS o en la última declaración de impuestos.',
    targetPath: 'entities.petitioner.ein',
    impactPath: 'entities.petitioner',
    kind: 'text',
    blocksLabel: 'Tab A completo',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q7',
    declaredBlocks: 3,
    order: 7,
    prompt: 'Del acta constitutiva de Cellular Hope Institute: fecha, número de escritura, notario, RFC y licencia COFEPRIS',
    weHad: 'Que CHI es una clínica y laboratorio de medicina regenerativa en Cancún.',
    whatAppearsNow: 'Acta constitutiva, RFC y licencia COFEPRIS: todos pendientes.',
    whyItMatters: 'La Tab B tiene que probar que la empleadora extranjera existe y opera de forma regular, sistemática y continua. Es el segundo de los cinco elementos.',
    clarifyingDocument: 'Acta constitutiva pasada ante notario, constancia de situación fiscal del SAT y licencia sanitaria COFEPRIS.',
    searchHint: 'El contador de CHI tiene la constancia de situación fiscal; el notario tiene copia del acta. La licencia COFEPRIS suele estar enmarcada en la clínica.',
    targetPath: 'entities.foreignEmployer.rfc',
    impactPath: 'entities.foreignEmployer',
    kind: 'text',
    blocksLabel: 'Tab B completo',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q8',
    declaredBlocks: 2,
    order: 8,
    prompt: '¿Ya está firmado el arrendamiento de Plantation y a nombre de qué entidad quedó?',
    weHad: 'Clínica nueva en 9633 W Broward Blvd, Suite 1, Plantation, FL. Debe salir a nombre de GSCG.',
    whatAppearsNow: 'No consta que esté firmado, ni a nombre de quién.',
    whyItMatters: 'La modalidad de oficina nueva exige local físico asegurado, y el titular del arrendamiento tiene que ser la misma entidad que presenta el I-129.',
    clarifyingDocument: 'Contrato de arrendamiento firmado de Plantation, FL, a nombre de Global Stem Cells Group, Inc.',
    searchHint: 'Pide al arrendador la versión firmada en PDF. Revisa en la primera página a nombre de qué entidad quedó el inquilino.',
    targetPath: 'usOffice.leaseSigned',
    impactPath: 'usOffice',
    kind: 'boolean',
    blocksLabel: 'Elemento de oficina nueva',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q9',
    declaredBlocks: 2,
    order: 9,
    prompt: '¿Cuál será tu salario propuesto en EE.UU. y a quién se piensa contratar en los primeros 12 meses?',
    weHad: 'Puesto propuesto: Chief Operating Officer & Managing Director of U.S. Operations.',
    whatAppearsNow: 'Sin salario propuesto y sin plan de contratación.',
    whyItMatters: 'Por ser oficina nueva hay que mostrar que la operación podrá sostener un puesto ejecutivo dentro de un año de la aprobación.',
    clarifyingDocument: 'Carta de oferta de GSCG + Business Plan con proyecciones y plan de contratación a 12 meses.',
    searchHint: 'Si ya hay una cifra hablada con Benito, anótala tal cual y marca de dónde salió.',
    targetPath: 'beneficiary.proposedSalary',
    impactPath: 'businessPlan',
    kind: 'money',
    blocksLabel: 'Business Plan, Tab F',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q10',
    declaredBlocks: 2,
    order: 10,
    prompt: '¿Cuántos empleados tiene Cellular Hope Institute y qué volumen aproximado de pacientes o ingresos anuales maneja?',
    weHad: 'CHI es clínica y laboratorio en Cancún, dentro de un grupo con operaciones en 9 países.',
    whatAppearsNow: 'Sin número de empleados y sin volumen de operación.',
    whyItMatters: 'Hay que probar que la empleadora extranjera hace negocio de forma regular, sistemática y continua. No basta existir en papel.',
    clarifyingDocument: 'Nómina completa de CHI + estados de cuenta bancarios + facturas de los últimos 2 años.',
    searchHint: 'El contador puede dar el número de altas en el IMSS y el total facturado del año pasado en una hoja.',
    targetPath: 'entities.foreignEmployer.employeeCount',
    kind: 'number',
    blocksLabel: 'Operación sistemática',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q11',
    declaredBlocks: 1,
    order: 11,
    prompt: 'Los recibos que al inicio se describieron como "de Cellgenic LLC", ¿qué entidad dicen en la cara del papel?',
    weHad: 'La empleadora extranjera es Cellular Hope Institute, S.A. de C.V., confirmado por ti.',
    whatAppearsNow: 'Hay recibos que se describieron como emitidos por Cellgenic LLC. Si la entidad pagadora del recibo no es la empleadora declarada, el expediente se contradice solo.',
    whyItMatters: 'Si el papel que prueba el empleo dice otra entidad, la relación laboral queda en duda justo donde más se mira.',
    clarifyingDocument: 'Recibo CFDI timbrado: leer el nombre y RFC del emisor en la cara del recibo.',
    searchHint: 'Abre el PDF de cualquier recibo y lee el bloque "Emisor". Copia el nombre exacto y el RFC, tal como están escritos.',
    targetPath: 'entities.foreignEmployer.payrollIssuer',
    kind: 'text',
    blocksLabel: 'Coherencia de nómina',
    status: 'open',
    generatedBy: 'seed',
  },
  {
    id: 'q12',
    declaredBlocks: 1,
    order: 12,
    prompt: '¿Aplicaste al pasaporte mexicano? (pregunta abierta de la abogada)',
    weHad: 'Eres venezolana, con visa de trabajo mexicana patrocinada por la empleadora extranjera.',
    whatAppearsNow: 'La abogada preguntó por el pasaporte mexicano y la pregunta sigue sin respuesta.',
    whyItMatters: 'La abogada la dejó abierta y afecta la planeación del trámite consular. Además hay que verificar con ella el estatus vigente de restricciones de viaje aplicables a nacionales venezolanos.',
    clarifyingDocument: 'Comprobante de cita o de solicitud ante la SRE, si existe.',
    searchHint: 'Si hay cita agendada, guarda el acuse con folio y fecha.',
    targetPath: 'beneficiary.mexicanPassport',
    kind: 'text',
    blocksLabel: 'Respuesta pendiente a la abogada',
    status: 'open',
    generatedBy: 'seed',
  },
];
